
SUBROUTINE GPRCP_YDVARS (KPROMA,KST,KPROF,KFLEV,PCP,PR,PKAP,YDVARS,PGFL,KGFLTYP)

!**** *GPRCP_YDVARS* - Computes Cp, R and R/Cp from Q

!     Purpose.
!     --------
!        Computes Cp, R and R/Cp from Q

!**   Interface.
!     ----------
!        *CALL* *GPRCP_YDVARS(...)

!        Explicit arguments :
!        --------------------

!        INPUT:
!          KPROMA               - dimensioning.
!          KSTART               - start of work.
!          KPROF                - depth of work.
!          KFLEV                - number of layers.

!        OUTPUT:
!          PCP(KPROMA,KFLEV)    - CP
!          PR(KPROMA,KFLEV)     - R
!          PKAP(KPROMA,KFLEV)   - KAPPA

!        Implicit arguments :  Physical constants from YOMCST
!        --------------------

!     Method.
!     -------
!        See documentation

!     Externals.  None.
!     ----------

!     Reference.
!     ----------
!        ECMWF Research Department documentation of the IFS

!     Author.
!     -------
!      Mats Hamrud and Philippe Courtier  *ECMWF*
!      Original : 88-02-04

!     Modifications.
!      M.Hamrud      01-Oct-2003 CY28 Cleaning
!      Y.Seity  04-02-13 (Rain, Snow and Graupel)
!      M.Hamrud  15-Jan-2006  Revised GPRCP
!      K. Yessad (Jan 2011): more compact rewriting.
!      R. El Khatib 28-Aug-2014 Optimizations :
!       - compute R or CP only if required
!       - loop collapsing whenever possible, through pure array syntax
!      A. Geer      01-Oct-2015    For independence of observation operator in OOPS, 
!                                  allow calls without YGFL initialised. Removal
!                                  of all YGFL references will have to wait.
!      H Petithomme (Dec 2020): general rewrite for optimization
!     ------------------------------------------------------------------

USE PARKIND1,ONLY: JPIM,JPRB
USE YOMHOOK,ONLY: LHOOK,DR_HOOK
USE YOMCST,ONLY: RD,RV,RCPD,RCPV,RCW,RCS
USE YOM_YGFL,ONLY: TYPE_GFLD,TYPE_GFL_COMP,YGFL
USE FIELD_VARIABLES_MOD,ONLY : FIELD_VARIABLES

USE YOMCT3   , ONLY : NSTEP

IMPLICIT NONE

INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA,KFLEV,KST,KPROF
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN) :: KGFLTYP
TYPE(FIELD_VARIABLES),INTENT(INOUT) :: YDVARS
REAL(KIND=JPRB),INTENT(IN) :: PGFL(KPROMA,KFLEV,YGFL%NDIM)
REAL(KIND=JPRB),OPTIONAL,TARGET,INTENT(OUT) :: PCP(KPROMA,KFLEV)
REAL(KIND=JPRB),OPTIONAL,TARGET,INTENT(OUT) :: PR(KPROMA,KFLEV)
REAL(KIND=JPRB),OPTIONAL,INTENT(OUT) :: PKAP(KPROMA,KFLEV)

#include "abor1.intfb.h"

REAL(KIND=JPRB),CONTIGUOUS,POINTER :: ZR(:,:)
REAL(KIND=JPRB),CONTIGUOUS,POINTER :: ZCP(:,:)

REAL(KIND=JPRB),TARGET :: ZCP0(KPROMA,KFLEV),ZR0(KPROMA,KFLEV)
REAL(KIND=JPRB) :: ZCP1(KPROMA,KFLEV),ZR1(KPROMA,KFLEV)
INTEGER(KIND=JPIM) :: IGFLTYP,JL,JP,JGFL,I,NACT,IPT(YGFL%NUMFLDS),JLON,JLEV
REAL(KIND=JPRB) :: YR(YGFL%NUMFLDS),YCP(YGFL%NUMFLDS)
LOGICAL :: LLR, LLCP
REAL(KIND=JPRB) :: ZHOOK

IF (LHOOK) CALL DR_HOOK("GPRCP_YDVARS",0,ZHOOK)

IF (PRESENT(PR)) THEN
  ZR => PR(:,:)
ELSEIF (PRESENT(PKAP)) THEN
  ZR => ZR0(:,:)
ENDIF

IF (PRESENT(PCP)) THEN
  ZCP => PCP(:,:)
ELSEIF (PRESENT(PKAP)) THEN
  ZCP => ZCP0(:,:)
ELSE
  ZCP => NULL()
ENDIF

ZCP = 0._JPRB
ZR = 0._JPRB

IGFLTYP = 0
IF (PRESENT (KGFLTYP)) IGFLTYP = KGFLTYP 

IF (NSTEP == 0) PRINT *, '------------------------------'

ZR1 = 0._JPRB
ZCP1 = 0._JPRB

  IF (YDVARS%Q%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR1 (JLON,JLEV) = ZR1 (JLON,JLEV) + (YDVARS%Q%R - RD) * YDVARS%Q%T0 (JLON, JLEV)
        ZCP1 (JLON,JLEV) = ZCP1 (JLON,JLEV) + (YDVARS%Q%RCP - RCPD) * YDVARS%Q%T0 (JLON, JLEV)
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%I%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR1 (JLON,JLEV) = ZR1 (JLON,JLEV) + (YDVARS%I%R - RD) * YDVARS%I%T0 (JLON, JLEV)
        ZCP1 (JLON,JLEV) = ZCP1 (JLON,JLEV) + (YDVARS%I%RCP - RCPD) * YDVARS%I%T0 (JLON, JLEV)
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%L%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR1 (JLON,JLEV) = ZR1 (JLON,JLEV) + (YDVARS%L%R - RD) * YDVARS%L%T0 (JLON, JLEV)
        ZCP1 (JLON,JLEV) = ZCP1 (JLON,JLEV) + (YDVARS%L%RCP - RCPD) * YDVARS%L%T0 (JLON, JLEV)
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%LCONV%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR1 (JLON,JLEV) = ZR1 (JLON,JLEV) + (YDVARS%LCONV%R - RD) * YDVARS%LCONV%T0 (JLON, JLEV)
        ZCP1 (JLON,JLEV) = ZCP1 (JLON,JLEV) + (YDVARS%LCONV%RCP - RCPD) * YDVARS%LCONV%T0 (JLON, JLEV)
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%ICONV%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR1 (JLON,JLEV) = ZR1 (JLON,JLEV) + (YDVARS%ICONV%R - RD) * YDVARS%ICONV%T0 (JLON, JLEV)
        ZCP1 (JLON,JLEV) = ZCP1 (JLON,JLEV) + (YDVARS%ICONV%RCP - RCPD) * YDVARS%ICONV%T0 (JLON, JLEV)
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%RCONV%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR1 (JLON,JLEV) = ZR1 (JLON,JLEV) + (YDVARS%RCONV%R - RD) * YDVARS%RCONV%T0 (JLON, JLEV)
        ZCP1 (JLON,JLEV) = ZCP1 (JLON,JLEV) + (YDVARS%RCONV%RCP - RCPD) * YDVARS%RCONV%T0 (JLON, JLEV)
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%SCONV%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR1 (JLON,JLEV) = ZR1 (JLON,JLEV) + (YDVARS%SCONV%R - RD) * YDVARS%SCONV%T0 (JLON, JLEV)
        ZCP1 (JLON,JLEV) = ZCP1 (JLON,JLEV) + (YDVARS%SCONV%RCP - RCPD) * YDVARS%SCONV%T0 (JLON, JLEV)
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%IRAD%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR1 (JLON,JLEV) = ZR1 (JLON,JLEV) + (YDVARS%IRAD%R - RD) * YDVARS%IRAD%T0 (JLON, JLEV)
        ZCP1 (JLON,JLEV) = ZCP1 (JLON,JLEV) + (YDVARS%IRAD%RCP - RCPD) * YDVARS%IRAD%T0 (JLON, JLEV)
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%LRAD%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR1 (JLON,JLEV) = ZR1 (JLON,JLEV) + (YDVARS%LRAD%R - RD) * YDVARS%LRAD%T0 (JLON, JLEV)
        ZCP1 (JLON,JLEV) = ZCP1 (JLON,JLEV) + (YDVARS%LRAD%RCP - RCPD) * YDVARS%LRAD%T0 (JLON, JLEV)
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%S%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR1 (JLON,JLEV) = ZR1 (JLON,JLEV) + (YDVARS%S%R - RD) * YDVARS%S%T0 (JLON, JLEV)
        ZCP1 (JLON,JLEV) = ZCP1 (JLON,JLEV) + (YDVARS%S%RCP - RCPD) * YDVARS%S%T0 (JLON, JLEV)
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%R%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR1 (JLON,JLEV) = ZR1 (JLON,JLEV) + (YDVARS%R%R - RD) * YDVARS%R%T0 (JLON, JLEV)
        ZCP1 (JLON,JLEV) = ZCP1 (JLON,JLEV) + (YDVARS%R%RCP - RCPD) * YDVARS%R%T0 (JLON, JLEV)
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%G%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR1 (JLON,JLEV) = ZR1 (JLON,JLEV) + (YDVARS%G%R - RD) * YDVARS%G%T0 (JLON, JLEV)
        ZCP1 (JLON,JLEV) = ZCP1 (JLON,JLEV) + (YDVARS%G%RCP - RCPD) * YDVARS%G%T0 (JLON, JLEV)
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%H%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR1 (JLON,JLEV) = ZR1 (JLON,JLEV) + (YDVARS%H%R - RD) * YDVARS%H%T0 (JLON, JLEV)
        ZCP1 (JLON,JLEV) = ZCP1 (JLON,JLEV) + (YDVARS%H%RCP - RCPD) * YDVARS%H%T0 (JLON, JLEV)
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%TKE%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR1 (JLON,JLEV) = ZR1 (JLON,JLEV) + (YDVARS%TKE%R - RD) * YDVARS%TKE%T0 (JLON, JLEV)
        ZCP1 (JLON,JLEV) = ZCP1 (JLON,JLEV) + (YDVARS%TKE%RCP - RCPD) * YDVARS%TKE%T0 (JLON, JLEV)
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%TTE%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR1 (JLON,JLEV) = ZR1 (JLON,JLEV) + (YDVARS%TTE%R - RD) * YDVARS%TTE%T0 (JLON, JLEV)
        ZCP1 (JLON,JLEV) = ZCP1 (JLON,JLEV) + (YDVARS%TTE%RCP - RCPD) * YDVARS%TTE%T0 (JLON, JLEV)
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%EFB1%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR1 (JLON,JLEV) = ZR1 (JLON,JLEV) + (YDVARS%EFB1%R - RD) * YDVARS%EFB1%T0 (JLON, JLEV)
        ZCP1 (JLON,JLEV) = ZCP1 (JLON,JLEV) + (YDVARS%EFB1%RCP - RCPD) * YDVARS%EFB1%T0 (JLON, JLEV)
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%EFB2%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR1 (JLON,JLEV) = ZR1 (JLON,JLEV) + (YDVARS%EFB2%R - RD) * YDVARS%EFB2%T0 (JLON, JLEV)
        ZCP1 (JLON,JLEV) = ZCP1 (JLON,JLEV) + (YDVARS%EFB2%RCP - RCPD) * YDVARS%EFB2%T0 (JLON, JLEV)
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%EFB3%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR1 (JLON,JLEV) = ZR1 (JLON,JLEV) + (YDVARS%EFB3%R - RD) * YDVARS%EFB3%T0 (JLON, JLEV)
        ZCP1 (JLON,JLEV) = ZCP1 (JLON,JLEV) + (YDVARS%EFB3%RCP - RCPD) * YDVARS%EFB3%T0 (JLON, JLEV)
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%A%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR1 (JLON,JLEV) = ZR1 (JLON,JLEV) + (YDVARS%A%R - RD) * YDVARS%A%T0 (JLON, JLEV)
        ZCP1 (JLON,JLEV) = ZCP1 (JLON,JLEV) + (YDVARS%A%RCP - RCPD) * YDVARS%A%T0 (JLON, JLEV)
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%O3%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR1 (JLON,JLEV) = ZR1 (JLON,JLEV) + (YDVARS%O3%R - RD) * YDVARS%O3%T0 (JLON, JLEV)
        ZCP1 (JLON,JLEV) = ZCP1 (JLON,JLEV) + (YDVARS%O3%RCP - RCPD) * YDVARS%O3%T0 (JLON, JLEV)
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%SRC%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR1 (JLON,JLEV) = ZR1 (JLON,JLEV) + (YDVARS%SRC%R - RD) * YDVARS%SRC%T0 (JLON, JLEV)
        ZCP1 (JLON,JLEV) = ZCP1 (JLON,JLEV) + (YDVARS%SRC%RCP - RCPD) * YDVARS%SRC%T0 (JLON, JLEV)
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%MXL%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR1 (JLON,JLEV) = ZR1 (JLON,JLEV) + (YDVARS%MXL%R - RD) * YDVARS%MXL%T0 (JLON, JLEV)
        ZCP1 (JLON,JLEV) = ZCP1 (JLON,JLEV) + (YDVARS%MXL%RCP - RCPD) * YDVARS%MXL%T0 (JLON, JLEV)
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%SHTUR%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR1 (JLON,JLEV) = ZR1 (JLON,JLEV) + (YDVARS%SHTUR%R - RD) * YDVARS%SHTUR%T0 (JLON, JLEV)
        ZCP1 (JLON,JLEV) = ZCP1 (JLON,JLEV) + (YDVARS%SHTUR%RCP - RCPD) * YDVARS%SHTUR%T0 (JLON, JLEV)
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%FQTUR%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR1 (JLON,JLEV) = ZR1 (JLON,JLEV) + (YDVARS%FQTUR%R - RD) * YDVARS%FQTUR%T0 (JLON, JLEV)
        ZCP1 (JLON,JLEV) = ZCP1 (JLON,JLEV) + (YDVARS%FQTUR%RCP - RCPD) * YDVARS%FQTUR%T0 (JLON, JLEV)
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%FSTUR%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR1 (JLON,JLEV) = ZR1 (JLON,JLEV) + (YDVARS%FSTUR%R - RD) * YDVARS%FSTUR%T0 (JLON, JLEV)
        ZCP1 (JLON,JLEV) = ZCP1 (JLON,JLEV) + (YDVARS%FSTUR%RCP - RCPD) * YDVARS%FSTUR%T0 (JLON, JLEV)
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%CPF%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR1 (JLON,JLEV) = ZR1 (JLON,JLEV) + (YDVARS%CPF%R - RD) * YDVARS%CPF%T0 (JLON, JLEV)
        ZCP1 (JLON,JLEV) = ZCP1 (JLON,JLEV) + (YDVARS%CPF%RCP - RCPD) * YDVARS%CPF%T0 (JLON, JLEV)
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%SPF%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR1 (JLON,JLEV) = ZR1 (JLON,JLEV) + (YDVARS%SPF%R - RD) * YDVARS%SPF%T0 (JLON, JLEV)
        ZCP1 (JLON,JLEV) = ZCP1 (JLON,JLEV) + (YDVARS%SPF%RCP - RCPD) * YDVARS%SPF%T0 (JLON, JLEV)
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%CVGQ%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR1 (JLON,JLEV) = ZR1 (JLON,JLEV) + (YDVARS%CVGQ%R - RD) * YDVARS%CVGQ%T0 (JLON, JLEV)
        ZCP1 (JLON,JLEV) = ZCP1 (JLON,JLEV) + (YDVARS%CVGQ%RCP - RCPD) * YDVARS%CVGQ%T0 (JLON, JLEV)
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%QVA%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR1 (JLON,JLEV) = ZR1 (JLON,JLEV) + (YDVARS%QVA%R - RD) * YDVARS%QVA%T0 (JLON, JLEV)
        ZCP1 (JLON,JLEV) = ZCP1 (JLON,JLEV) + (YDVARS%QVA%RCP - RCPD) * YDVARS%QVA%T0 (JLON, JLEV)
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%LRCH4%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR1 (JLON,JLEV) = ZR1 (JLON,JLEV) + (YDVARS%LRCH4%R - RD) * YDVARS%LRCH4%T0 (JLON, JLEV)
        ZCP1 (JLON,JLEV) = ZCP1 (JLON,JLEV) + (YDVARS%LRCH4%RCP - RCPD) * YDVARS%LRCH4%T0 (JLON, JLEV)
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%PHYCTY%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR1 (JLON,JLEV) = ZR1 (JLON,JLEV) + (YDVARS%PHYCTY%R - RD) * YDVARS%PHYCTY%T0 (JLON, JLEV)
        ZCP1 (JLON,JLEV) = ZCP1 (JLON,JLEV) + (YDVARS%PHYCTY%RCP - RCPD) * YDVARS%PHYCTY%T0 (JLON, JLEV)
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%RSPEC%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR1 (JLON,JLEV) = ZR1 (JLON,JLEV) + (YDVARS%RSPEC%R - RD) * YDVARS%RSPEC%T0 (JLON, JLEV)
        ZCP1 (JLON,JLEV) = ZCP1 (JLON,JLEV) + (YDVARS%RSPEC%RCP - RCPD) * YDVARS%RSPEC%T0 (JLON, JLEV)
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%SDSAT%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR1 (JLON,JLEV) = ZR1 (JLON,JLEV) + (YDVARS%SDSAT%R - RD) * YDVARS%SDSAT%T0 (JLON, JLEV)
        ZCP1 (JLON,JLEV) = ZCP1 (JLON,JLEV) + (YDVARS%SDSAT%RCP - RCPD) * YDVARS%SDSAT%T0 (JLON, JLEV)
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%CVV%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR1 (JLON,JLEV) = ZR1 (JLON,JLEV) + (YDVARS%CVV%R - RD) * YDVARS%CVV%T0 (JLON, JLEV)
        ZCP1 (JLON,JLEV) = ZCP1 (JLON,JLEV) + (YDVARS%CVV%RCP - RCPD) * YDVARS%CVV%T0 (JLON, JLEV)
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%RKTH%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR1 (JLON,JLEV) = ZR1 (JLON,JLEV) + (YDVARS%RKTH%R - RD) * YDVARS%RKTH%T0 (JLON, JLEV)
        ZCP1 (JLON,JLEV) = ZCP1 (JLON,JLEV) + (YDVARS%RKTH%RCP - RCPD) * YDVARS%RKTH%T0 (JLON, JLEV)
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%RKTQV%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR1 (JLON,JLEV) = ZR1 (JLON,JLEV) + (YDVARS%RKTQV%R - RD) * YDVARS%RKTQV%T0 (JLON, JLEV)
        ZCP1 (JLON,JLEV) = ZCP1 (JLON,JLEV) + (YDVARS%RKTQV%RCP - RCPD) * YDVARS%RKTQV%T0 (JLON, JLEV)
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%RKTQC%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR1 (JLON,JLEV) = ZR1 (JLON,JLEV) + (YDVARS%RKTQC%R - RD) * YDVARS%RKTQC%T0 (JLON, JLEV)
        ZCP1 (JLON,JLEV) = ZCP1 (JLON,JLEV) + (YDVARS%RKTQC%RCP - RCPD) * YDVARS%RKTQC%T0 (JLON, JLEV)
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%UOM%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR1 (JLON,JLEV) = ZR1 (JLON,JLEV) + (YDVARS%UOM%R - RD) * YDVARS%UOM%T0 (JLON, JLEV)
        ZCP1 (JLON,JLEV) = ZCP1 (JLON,JLEV) + (YDVARS%UOM%RCP - RCPD) * YDVARS%UOM%T0 (JLON, JLEV)
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%UAL%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR1 (JLON,JLEV) = ZR1 (JLON,JLEV) + (YDVARS%UAL%R - RD) * YDVARS%UAL%T0 (JLON, JLEV)
        ZCP1 (JLON,JLEV) = ZCP1 (JLON,JLEV) + (YDVARS%UAL%RCP - RCPD) * YDVARS%UAL%T0 (JLON, JLEV)
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%DOM%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR1 (JLON,JLEV) = ZR1 (JLON,JLEV) + (YDVARS%DOM%R - RD) * YDVARS%DOM%T0 (JLON, JLEV)
        ZCP1 (JLON,JLEV) = ZCP1 (JLON,JLEV) + (YDVARS%DOM%RCP - RCPD) * YDVARS%DOM%T0 (JLON, JLEV)
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%DAL%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR1 (JLON,JLEV) = ZR1 (JLON,JLEV) + (YDVARS%DAL%R - RD) * YDVARS%DAL%T0 (JLON, JLEV)
        ZCP1 (JLON,JLEV) = ZCP1 (JLON,JLEV) + (YDVARS%DAL%RCP - RCPD) * YDVARS%DAL%T0 (JLON, JLEV)
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%UEN%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR1 (JLON,JLEV) = ZR1 (JLON,JLEV) + (YDVARS%UEN%R - RD) * YDVARS%UEN%T0 (JLON, JLEV)
        ZCP1 (JLON,JLEV) = ZCP1 (JLON,JLEV) + (YDVARS%UEN%RCP - RCPD) * YDVARS%UEN%T0 (JLON, JLEV)
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%UNEBH%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR1 (JLON,JLEV) = ZR1 (JLON,JLEV) + (YDVARS%UNEBH%R - RD) * YDVARS%UNEBH%T0 (JLON, JLEV)
        ZCP1 (JLON,JLEV) = ZCP1 (JLON,JLEV) + (YDVARS%UNEBH%RCP - RCPD) * YDVARS%UNEBH%T0 (JLON, JLEV)
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%FSD%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR1 (JLON,JLEV) = ZR1 (JLON,JLEV) + (YDVARS%FSD%R - RD) * YDVARS%FSD%T0 (JLON, JLEV)
        ZCP1 (JLON,JLEV) = ZCP1 (JLON,JLEV) + (YDVARS%FSD%RCP - RCPD) * YDVARS%FSD%T0 (JLON, JLEV)
      ENDDO
    ENDDO
  ENDIF

DO JLEV = 1, KFLEV
  DO JLON = KST, KPROF
    ZR1 (JLON,JLEV) = RD + ZR1 (JLON,JLEV)
    ZCP1 (JLON,JLEV) = RCPD + ZCP1 (JLON,JLEV)
  ENDDO
ENDDO



NACT = 0
IF (IGFLTYP == 0) THEN
  DO JGFL=1,YGFL%NUMFLDS
    IF (.NOT.YGFL%YCOMP(JGFL)%LTHERMACT) CYCLE

    NACT = NACT+1
    IPT(NACT) = YGFL%YCOMP(JGFL)%MP
    YR(NACT) = YGFL%YCOMP(JGFL)%R
    YCP(NACT) = YGFL%YCOMP(JGFL)%RCP

IF (NSTEP == 0) PRINT *, JGFL, YGFL%YCOMP(JGFL)%CNAME

  ENDDO
ELSEIF (IGFLTYP == 1) THEN
  DO JGFL=1,YGFL%NUMFLDS
    IF (.NOT.YGFL%YCOMP(JGFL)%LTHERMACT) CYCLE

    NACT = NACT+1
    IPT(NACT) = YGFL%YCOMP(JGFL)%MP1
    YR(NACT) = YGFL%YCOMP(JGFL)%R
    YCP(NACT) = YGFL%YCOMP(JGFL)%RCP
  ENDDO
ELSEIF (IGFLTYP == 5) THEN
  DO JGFL=1,YGFL%NUMFLDS
    IF (.NOT.YGFL%YCOMP(JGFL)%LTHERMACT) CYCLE

    NACT = NACT+1
    IPT(NACT) = YGFL%YCOMP(JGFL)%MP5
    YR(NACT) = YGFL%YCOMP(JGFL)%R
    YCP(NACT) = YGFL%YCOMP(JGFL)%RCP
  ENDDO
ELSEIF (IGFLTYP == 9) THEN
  DO JGFL=1,YGFL%NUMFLDS
    IF (.NOT.YGFL%YCOMP(JGFL)%LTHERMACT) CYCLE

    NACT = NACT+1
    IPT(NACT) = YGFL%YCOMP(JGFL)%MP9_PH
    YR(NACT) = YGFL%YCOMP(JGFL)%R
    YCP(NACT) = YGFL%YCOMP(JGFL)%RCP
  ENDDO
ELSEIF (IGFLTYP == 101) THEN
  DO JGFL=1,YGFL%NUMFLDS
    IF (.NOT.YGFL%YCOMP(JGFL)%LTHERMACT) CYCLE

    NACT = NACT+1
    IPT(NACT) = YGFL%YCOMP(JGFL)%MP_SL1
    YR(NACT) = YGFL%YCOMP(JGFL)%R
    YCP(NACT) = YGFL%YCOMP(JGFL)%RCP
  ENDDO
ELSE
  CALL ABOR1("UNKNOWN GFL TYPE")
ENDIF


LLR = ASSOCIATED(ZR)
LLCP = ASSOCIATED(ZCP)

! note: mind the brackets on PGFL, in order to add RD at last (precise computes)
! optim: explicit treatment of cases 0, 1, 2 and 3 (fewer loops)
IF (NACT == 0) THEN
  IF (LLR) THEN
    ZR(KST:KPROF,1:KFLEV) = RD
  ENDIF
  IF (LLCP) THEN
    ZCP(KST:KPROF,1:KFLEV) = RCPD
  ENDIF
ELSE IF (NACT == 1) THEN
  IF (LLR) THEN
    ZR(KST:KPROF,1:KFLEV) = RD+(YR(1)-RD)*PGFL(KST:KPROF,1:KFLEV,IPT(1))
  ENDIF
  IF (LLCP) THEN
    ZCP(KST:KPROF,1:KFLEV) = RCPD+(YCP(1)-RCPD)*PGFL(KST:KPROF,1:KFLEV,IPT(1))
  ENDIF
ELSE IF (NACT == 2) THEN
  IF (LLR) THEN
    ZR(KST:KPROF,1:KFLEV) = RD+((YR(1)-RD)*PGFL(KST:KPROF,1:KFLEV,IPT(1))+&
     & (YR(2)-RD)*PGFL(KST:KPROF,1:KFLEV,IPT(2)))
  ENDIF
  IF (LLCP) THEN
    ZCP(KST:KPROF,1:KFLEV) = RCPD+((YCP(1)-RCPD)*PGFL(KST:KPROF,1:KFLEV,IPT(1))+&
     & (YCP(2)-RCPD)*PGFL(KST:KPROF,1:KFLEV,IPT(2)))
  ENDIF
ELSE IF (NACT == 3) THEN
  IF (LLR) THEN
    ZR(KST:KPROF,1:KFLEV) = RD+((YR(1)-RD)*PGFL(KST:KPROF,1:KFLEV,IPT(1))+&
     & (YR(2)-RD)*PGFL(KST:KPROF,1:KFLEV,IPT(2))+&
     & (YR(3)-RD)*PGFL(KST:KPROF,1:KFLEV,IPT(3)))
  ENDIF
  IF (LLCP) THEN
    ZCP(KST:KPROF,1:KFLEV) = RCPD+((YCP(1)-RCPD)*PGFL(KST:KPROF,1:KFLEV,IPT(1))+&
     & (YCP(2)-RCPD)*PGFL(KST:KPROF,1:KFLEV,IPT(2))+&
     & (YCP(3)-RCPD)*PGFL(KST:KPROF,1:KFLEV,IPT(3)))
  ENDIF
ELSE
  IF (LLR) THEN
    ZR(KST:KPROF,1:KFLEV) = (YR(1)-RD)*PGFL(KST:KPROF,1:KFLEV,IPT(1))+&
     & (YR(2)-RD)*PGFL(KST:KPROF,1:KFLEV,IPT(2))+&
     & (YR(3)-RD)*PGFL(KST:KPROF,1:KFLEV,IPT(3))
  ENDIF
  IF (LLCP) THEN
    ZCP(KST:KPROF,1:KFLEV) = (YCP(1)-RCPD)*PGFL(KST:KPROF,1:KFLEV,IPT(1))+&
     & (YCP(2)-RCPD)*PGFL(KST:KPROF,1:KFLEV,IPT(2))+&
     & (YCP(3)-RCPD)*PGFL(KST:KPROF,1:KFLEV,IPT(3))
  ENDIF

  DO I=4,NACT-1
    IF (LLR) THEN
      ZR(KST:KPROF,1:KFLEV) = ZR(KST:KPROF,1:KFLEV)+&
        (YR(I)-RD)*PGFL(KST:KPROF,1:KFLEV,IPT(I))
    ENDIF
    IF (LLCP) THEN
      ZCP(KST:KPROF,1:KFLEV) = ZCP(KST:KPROF,1:KFLEV)+(YCP(I)-RCPD)*&
       & PGFL(KST:KPROF,1:KFLEV,IPT(I))
    ENDIF
  ENDDO

  I=NACT
  IF (LLR) THEN
    ZR(KST:KPROF,1:KFLEV) = RD+(ZR(KST:KPROF,1:KFLEV)+&
        (YR(I)-RD)*PGFL(KST:KPROF,1:KFLEV,IPT(I)))
  ENDIF
  IF (LLCP) THEN
    ZCP(KST:KPROF,1:KFLEV) = RCPD+(ZCP(KST:KPROF,1:KFLEV)+(YCP(I)-RCPD)*&
     & PGFL(KST:KPROF,1:KFLEV,IPT(I)))
  ENDIF
ENDIF

PRINT *, '--- ZCP ---'
DO JLEV = 1, KFLEV
  JLON = 1
  WRITE (*, '(I6," ",2E30.20," ",I6," ",E12.5)') JLEV, ZCP (JLON, JLEV), ZCP1 (JLON, JLEV), &
 & COUNT (ZCP /= ZCP1), MAXVAL (ABS (ZCP - ZCP1))
ENDDO

PRINT *, '--- ZR ---'
DO JLEV = 1, KFLEV
  JLON = 1
  WRITE (*, '(I6," ",2E30.20," ",I6," ",E12.5)') JLEV, ZR (JLON, JLEV), ZR1 (JLON, JLEV), &
 & COUNT (ZR /= ZR1), MAXVAL (ABS (ZR - ZR1))
ENDDO



IF (PRESENT(PKAP)) PKAP(KST:KPROF,1:KFLEV)=ZR(KST:KPROF,1:KFLEV)/ZCP(KST:KPROF,1:KFLEV)

IF (LHOOK) CALL DR_HOOK("GPRCP_YDVARS",1,ZHOOK)

END SUBROUTINE GPRCP_YDVARS

